In [1]:
import pandas as pd
import numpy as np 
from keras.layers import Dense , SimpleRNN , GRU , LSTM , Embedding
from keras.models import Sequential
from tensorflow.keras.utils import to_categorical

In [2]:
amazon_foodreview = pd.read_csv(r"D:\data set\Amazon Food Reviews.csv")

In [3]:
amazon_foodreview.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [4]:
amazon_foodreview.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator', 'Score', 'Time', 'Summary', 'Text'],
      dtype='object')

In [5]:
amazon_foodreview=amazon_foodreview.drop(columns={'Id', 'ProductId', 'UserId', 'ProfileName', 'HelpfulnessNumerator',
       'HelpfulnessDenominator','Time', 'Summary'},axis=1)

In [6]:
amazon_foodreview.Score.value_counts()

5    363122
4     80655
1     52268
3     42640
2     29769
Name: Score, dtype: int64

In [7]:
amazon_foodreview.Score.replace({2:1,3:2,4:3,5:3},inplace=True)

In [8]:
amazon_foodreview.head()

Score                                               Text
0      3  I have bought several of the Vitality canned d...
1      1  Product arrived labeled as Jumbo Salted Peanut...
2      3  This is a confection that has been around a fe...
3      1  If you are looking for the secret ingredient i...
4      3  Great taffy at a great price.  There was a wid...

In [9]:
amazon_foodreview_x = amazon_foodreview.iloc[ : ,1]
amazon_foodreview_y = amazon_foodreview.iloc[ : ,0]

In [10]:
from sklearn.model_selection import train_test_split

train_x , test_x , train_y , test_y = train_test_split( amazon_foodreview_x , amazon_foodreview_y , test_size= 0.2) 

In [11]:
train_y  = to_categorical( train_y)
test_y   = to_categorical(test_y)

In [12]:
train_y.shape

(454763, 4)

In [13]:
train_y=train_y[:,1:]
test_y=test_y[:,1:]

In [14]:
test_y.shape

(113691, 3)

In [15]:
max_num_words = 20000    ## How many words do we consider from the entire CORPUS
seq_len = 100  ## How many tokens ( words to consider the each documnet / messages)
embedding_size = 200  ## vector lengths of each word

In [16]:
from keras.preprocessing.text import Tokenizer  # is used to tokinization ( it gives number to each and every words. )
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam

In [17]:
tokenizer = Tokenizer(num_words = max_num_words)
# tokenizer.fit_on_texts(amazon_foodreview.Text)
train_x = tokenizer.texts_to_sequences(train_x) # will convert the text to sequences of IDs
train_x = pad_sequences(train_x , maxlen = seq_len)

In [22]:
train_x[67]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
test_x  =  tokenizer.texts_to_sequences(test_x)
test_x  =  pad_sequences(test_x , maxlen = seq_len)

In [23]:
test_x[456]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
train_x[348]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
model = Sequential()  # iniitialize the network
model.add(Embedding(input_dim = max_num_words,    
                   input_length = seq_len,
                    output_dim = embedding_size))

In [25]:
model.add(LSTM(5)) 
model.add(Dense(3 , activation  = 'softmax'))  # this 2 bcoz u have 2 level in target variable



adam = Adam(lr = .001)


model.compile(optimizer= 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])

C:\Users\Priti\anaconda3\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [50]:
model.fit(train_x , train_y , epochs = 10 , batch_size= 250, validation_split= .2)

Epoch 1/10
1456/1456 [==============================] - 187s 128ms/step - loss: 0.3851 - accuracy: 0.8592 - val_loss: 0.3379 - val_accuracy: 0.8772
Epoch 2/10
1456/1456 [==============================] - 179s 123ms/step - loss: 0.2967 - accuracy: 0.8920 - val_loss: 0.3120 - val_accuracy: 0.8885
Epoch 3/10
1456/1456 [==============================] - 178s 122ms/step - loss: 0.2478 - accuracy: 0.9108 - val_loss: 0.2987 - val_accuracy: 0.8943
Epoch 4/10
1456/1456 [==============================] - 170s 117ms/step - loss: 0.2133 - accuracy: 0.9239 - val_loss: 0.3010 - val_accuracy: 0.8961
Epoch 5/10
1456/1456 [==============================] - 168s 116ms/step - loss: 0.1885 - accuracy: 0.9336 - val_loss: 0.3124 - val_accuracy: 0.8956
Epoch 6/10
1456/1456 [==============================] - 165s 113ms/step - loss: 0.1695 - accuracy: 0.9408 - val_loss: 0.3263 - val_accuracy: 0.8971
Epoch 7/10
1456/1456 [==============================] - 166s 114ms/step - loss: 0.1528 - accuracy: 0.9473 - val_

In [58]:
pred_test = model.predict(test_x)
pred_test

array([[9.9957753e-05, 7.2818319e-03, 9.9261826e-01],
       [4.1360130e-05, 3.7261270e-04, 9.9958605e-01],
       [1.9373246e-02, 9.6201159e-02, 8.8442564e-01],
       ...,
       [9.6349186e-01, 3.6039535e-02, 4.6858715e-04],
       [9.5488018e-01, 3.7389665e-03, 4.1380867e-02],
       [6.8667674e-01, 1.4911076e-01, 1.6421244e-01]], dtype=float32)

In [59]:
pred_test_c=np.argmax(pred_test,axis=1)
pred_test_c

array([2, 2, 2, ..., 0, 0, 0], dtype=int64)

In [60]:
test_y_c=np.argmax(test_y,axis=1)
test_y_c

array([2, 2, 2, ..., 0, 1, 0], dtype=int64)

In [61]:
from sklearn.metrics import *

In [62]:
tab=confusion_matrix(test_y_c,pred_test_c)
tab

array([[13284,  1352,  1808],
       [ 1888,  4307,  2365],
       [ 2310,  2731, 83646]], dtype=int64)

In [63]:
acc=accuracy_score(test_y_c,pred_test_c)
acc*100

89.04574680493619